---
title: "data_viz"
author: "tu"
date: "7/23/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(colorspace)
library(ragg)
library(ggtext)
library(cowplot)

theme_set(theme_minimal())
data <- tidytuesdayR::tt_load(2020, week = 18)

grosses <- data$grosses
```
```{r fig.height=50, fig.width=18}
p0 <- 
grosses %>% 
  inner_join(tony_award) %>% 
  mutate(theatre = str_remove(theatre, " Theatre"),
         week_ending = as.Date(week_ending)) %>%
  ggplot(aes(x =week_ending)) +
  # geom_point(
  #   aes(
  #     color = show
  #   ),
  #   shape = "|",
  #   size = 5,
  #   alpha = .33
  #  ) +
  geom_col(
    aes(
      y = avg_ticket_price,
      fill = show
    ),
    width = 1.5
  )+
  # facet_wrap(vars(show), scales = "free") +

  # ggdist::stat_halfeye(
  #   aes(
  #     color = show
  #   ),
  #   shape = 18,
  #   point_size = 3,
  #   interval_size = 1.8,
  #   adjust = .5,
  #   .width = c(0, 1)
  # ) +
  theme_void() +
  theme(legend.position = "none") +
  facet_grid(rows = vars(show))
```

```{r}
  ggplot(g %>% filter(show == "The Lion King"),aes(x = week_ending)) +
  geom_point(
    aes(
      
      color = show
    ),
    shape = "|",
    size = 5,
    alpha = .33
   ) +
  theme_void() +
  theme(legend.position = "none") 
  
```
```{r fig.height=50, fig.width=18}
get_panel()
 combined_plot <- insert_xaxis_grob(p1, p2, position = "bottom")
# 
# ggdraw(combined_plot)
```
```{r}
annotation_custom2 <- function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, data) 
{
  layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn,
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))
}
```


```{r fig.height=15, fig.width=18}
p1 +
  annotation_custom(grob=ggplotGrob(p2),
                     #data = data.frame(show="The Lion King"),
                      ymin = -100000, ymax=0, xmin= as.Date('1985-06-09'), xmax=as.Date('2020-03-01'))
```



```{r fig.height=12, fig.width=12}
pal <- c("#FF8C00", "#A034F0", "#159090")
df_penguins <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv') %>% 
  mutate(species = if_else(species == "Adelie", "Adélie", species))

df_peng_iqr <- 
  df_penguins %>% 
  mutate(bill_ratio = bill_length_mm / bill_depth_mm) %>% 
  filter(!is.na(bill_ratio)) %>% 
  group_by(species) %>% 
  mutate(
    median = median(bill_ratio),
    q25 = quantile(bill_ratio, probs = .25),
    q75 = quantile(bill_ratio, probs = .75),
    n = n()
  ) %>% 
  ungroup() %>% 
  mutate(species_num = as.numeric(fct_rev(species))) 

#rain <- 
ggplot(df_peng_iqr, aes(bill_ratio, species_num - .2)) +
  #这个居然是？？间隔型的barplot
  geom_point(
    aes(
      color = species
    ),
    shape = "|",
    size = 5,
    alpha = .33
  ) +
  ggdist::stat_halfeye(
    aes(
      y = species_num,
      color = species,
      fill = after_scale(lighten(color, .5))
    ),
    shape = 18,
    point_size = 3,
    interval_size = 1.8,
    adjust = .5,
    .width = c(0, 1)
  )

```









