---
title: "new_eda"
author: "tu"
date: "7/25/2020"
output: html_document
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(lubridate)

theme_set(theme_minimal())

data <- tidytuesdayR::tt_load(2020, week = 18)

#pre1985 <- data$`pre-1985-starts`
grosses <- data$grosses

```

```{r}
grosses %>% 
  group_by(show) %>% 
  summarise(total_preview = sum(previews),
            total_gross = sum(weekly_gross)) %>% 
  
  ggplot()+
  geom_density(aes(total_preview))
```

# what is the preview distribution among awarding winning musicals?
```{r}
grosses %>% 
  inner_join(tony_award, by = "show") %>% 
  group_by(show) %>% 
  summarise(total_preview = sum(previews),
            total_gross = sum(weekly_gross)) %>% 
  
  ggplot()+
  geom_density(aes(total_preview)) +
  scale_x_continuous(limits = c(0, 150))
```

Most award-winning shows' previews are like a normal distributions

## how about previews vs weekly-grosses?
```{r}
p <- grosses %>% 
  inner_join(tony_award, by = "show") %>% 
  group_by(show) %>% 
  summarise(total_preview = sum(previews),
            total_gross = sum(weekly_gross)) %>% 
  
  ggplot()+
  geom_point(aes(total_preview, total_gross, colour = show)) +
  geom_hline(yintercept=3.0e+08, size = 2, colour = "red") +
  theme(legend.position = 'none')

plotly::ggplotly(p)
```

## THOSE non-award winning shows?
```{r}
grosses %>% 
  group_by(show) %>% 
  summarise(total_preview = sum(previews),
            total_gross = sum(weekly_gross)) %>% 
  anti_join(tony_award, by = "show") %>%
  
  ggplot()+
  geom_density(aes(total_preview))
```
```{r}
p0 <- grosses %>% 
  anti_join(tony_award, by = "show") %>% 
  group_by(show) %>% 
  summarise(total_preview = sum(previews),
            total_gross = sum(weekly_gross)) %>% 
  
  ggplot()+
  geom_point(aes(total_preview, total_gross, colour = show)) +
 # geom_hline(yintercept=3.50e+08, size = 3, colour = "red") +
  theme(legend.position = 'none')

plotly::ggplotly(p0)
```



## how about weekly previews vs weekly gross

```{r}
p1 <- grosses %>% 
  inner_join(tony_award, by = "show") %>%
  group_by(show, week_ending) %>% 
  summarise(total_preview = sum(previews),
            total_gross = sum(weekly_gross)) %>% 
  ggplot()+
  geom_jitter(aes(total_preview, total_gross, colour = show)) +
  theme(legend.position = 'none')

```

```{r}
grosses %>% 
  anti_join(tony_award, by = "show") %>%
  group_by(show, week_ending) %>% 
  summarise(total_preview = sum(previews),
            total_gross = sum(weekly_gross)) %>% 
  ggplot()+
  geom_jitter(aes(total_preview, total_gross))
```
```{r fig.height=15, fig.width=15}
tony_award %>% 
  anti_join(grosses)
```

```{r fig.height=15, fig.width=18}
grosses %>% 
  inner_join(tony_award) %>% 
  #filter(show %in% c("Chicago", "The Lion King")) %>%
  mutate(year = year(date(week_ending)),
         month = month(date(week_ending))) %>%
  group_by(show, week_number) %>% 
  summarise(sum_gross = sum(weekly_gross)) %>% 
  ggplot()+
  geom_point(aes(week_number, show, size = sum_gross, alpha = sum_gross))
  
```


## Now i wonder availablity
```{r fig.height=15, fig.width=20}
grosses %>% 
  inner_join(tony_award) %>% 
  filter(show %in% c("The Lion King")) %>%
  mutate(year = year(date(week_ending)),
         month = month(date(week_ending)),
         available_seats = seats_sold * (1 - pct_capacity)) %>%
  group_by(show, year, week_number) %>% 
  summarise(seats = sum(available_seats)) %>% 
  mutate(seat_for_you = if_else(seats > 0, "YES", "NO")) %>% 
  #mutate(date = make_date(year, month)) %>% 
  ggplot()+
  geom_poit(aes(week_number, year, size = seats, color= seat_for_you), alpha=0.7) +
  #scale_size(values = c(range = c(0.1, 16)) +
  scale_color_manual(values = c("red", "#ffa500"))+
  theme(legend.position = 'none')
  
```
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(viridis)
library(lubridate)
library(gganimate)
library(ggtext)
library(ggbeeswarm)
theme_set(theme_classic())
```
```{r}
data <- tidytuesdayR::tt_load(2020, week = 18)

#pre1985 <- data$`pre-1985-starts`
grosses <- data$grosses
```
```{r}
top_100 <- grosses %>% 
  group_by(show) %>% 
  summarise(total_performance = sum(performances+previews)) %>% 
  arrange(desc(total_performance)) %>% 
  slice(c(1:100)) %>% 
  select(show)
```

```{r fig.height=14, fig.width=16}
grosses %>% 
  inner_join(tony_award, by = "show") %>% 
  mutate(theatre = str_remove(theatre, " Theatre"),
         week_ending = as.Date(week_ending)) %>% 
  mutate(total_performance = performances + previews) %>% 
  ggplot(aes(x = week_ending, y = theatre, colour = factor(show)))+
  geom_point(alpha = 0.35,shape = "|") +
  ggridges::geom_density_ridges_gradient(
    aes(
      x = theatre,
      y = weekly_gross,
      fill = weekly_gross
  )
  )+
  scale_size(range = c(1,2))+
  scale_x_date(labels = date_format("%Y"),
               date_breaks = "1 year",
               expand = c(0,0))+

  labs(x = NULL, y = NULL,
       title = "What have Broadway theatres been presenting to us in the past 35 years?",
       subtitle = "And here's a neat subtitle",
       caption = "Source: The Gapminder Project") +
  theme(legend.position = 'none')
  # transition_time(as.Date(week_ending)) +
  # shadow_mark()
# 
#plotly::ggplotly(p, width = 1600, height = 1000)
  
```
## 一个剧院每周一共多少演出，又有多少贡献给了某个剧，演出数量是不是和pct_capacity有关，还是weekly gross

```{r}
#d1 <- 
  grosses %>% 
  inner_join(tony_award) %>% 
  group_by(theatre, show) %>% 
  summarise(across(c("performances", "weekly_gross"), sum),
            median_ticket = median(avg_ticket_price)) %>% 
  ungroup() %>% 
  filter(median_ticket < 80) %>% 
  right_join(grosses, by = c('theatre' = 'theatre', 'show' = 'show')) %>% 
  filter(pct_capacity < 0.9)
  
```

```{r fig.height=8, fig.width=16}
p <- d1 %>% 
  group_by(theatre) %>% 
  summarise(total_profit = sum(weekly_gross),
            n = n()) %>% 
  ggplot() +
  geom_point(aes(total_profit,n, color = theatre)) +
  theme(legend.position = "none")

plotly::ggplotly(p)
```

## how about profit

```{r fig.height=15, fig.width=12}
d1 %>% 
  group_by(theatre) %>% 
  tally() %>% 
  ggplot()+
  geom_col(aes(n, reorder(theatre,n)))

```

