---
title: "aaaaaaaaaa"
author: "tu"
date: "8/3/2020"
output: html_document
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(colorspace)
library(ragg)
library(ggtext)
library(lubridate)

theme_set(theme_minimal())
data <- tidytuesdayR::tt_load(2020, week = 18)

grosses <- data$grosses
```
```{r}
cols <- c(
      "Most Profitable" = '#FFF7B9',
      "YES" = "#F3DF6F",
      'NO' = '#D9DACE'
)
```

```{r}
most_profit <- 
grosses %>% 
  group_by(theatre,show) %>% 
  summarise(profits = sum(weekly_gross)) %>% 
  #rowwise() %>% 
  group_by(theatre) %>% 
  mutate(most_profitable = if_else(profits == max(profits), "Most Profitable", "")) %>% 
  filter(most_profitable == "Most Profitable")

```
```{r}

stars<- 
  grosses %>% 
  right_join(most_profit, by = c('theatre', "show")) %>% 
  group_by(theatre, show) %>% 
  arrange(desc(week_ending)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  left_join(tony_award) %>%
  transmute(show, most_profitable, date = as.Date(week_ending), 
            total_p = performances + previews,
            theatre, 
            award = replace_na(award, "NO")) %>% 
  arrange(desc(date)) %>% 
  mutate(theatre_star = str_remove(fct_relevel(theatre, theatre), " Theatre")
         ) 

```
```{r}
plot_data <- 
grosses %>%
  group_by(theatre,show) %>% 
  summarise(profits = sum(weekly_gross)) %>% 
  ungroup() %>% 
  full_join(grosses) %>%
  full_join(stars) %>% 
  transmute(
                  week_date = as.Date(week_ending),
                  show, seats_sold, pct_capacity, profits, date,
                  most_profitable = replace_na(most_profitable, "NO"),
                  award = replace_na(award, "NO"),
                  total_perform = performances + previews,
                  theatre = str_remove(fct_relevel(theatre, levels(stars$theatre)), " Theatre"),
                  theatre_star,
                  #theatre_color = glue::glue("<i style = 'font-size:20pt; color:#FFF7B9'>{theatre}</i>")
  ) 
```
```{r}
ggplot()+
geom_point(
    data = plot_data %>%
            filter(most_profitable == "Most Profitable" &
                    !is.na(date)),
    aes(
      reorder(theatre, desc(date)),
      date,
      size = profits,
      color = award
    ),
    alpha = 0.79，
    shape = "☆"
  ) +
theme(
  legend.position = "none"
)
```
```{r}
plot_data %>%
            filter(most_profitable == "Most Profitable" &
                    !is.na(date)) %>% 
  distinct(most_profitable)
```

```{r fig.height=30, fig.width=50, warning=TRUE}
ggplot(data = plot_data)+
  geom_point(
    aes(
      theatre,
      week_date,
      size = profits,
      color = most_profitable,
      alpha = total_perform
    ),
    position = position_jitterdodge(
      jitter.width = 0.98,
      jitter.height = 0.4,
      dodge.width = 0.55
    )
  ) +
  geom_step(
    data = plot_data %>% 
            filter(most_profitable == "Most Profitable"),
    aes(
      theatre,
      week_date
    ),
    color = "#FFF7B9",
    size = 5,
    alpha = 0.8
  )+
  scale_alpha_continuous(
    limits = c(0.58, 0.88)
  )+
  scale_colour_manual(
    values = cols
    )+
  scale_size(
    range = c(0.8,1.5)
  )+
  ggnewscale::new_scale("size")+
  # the most profitable bubbles ma  should refer to when the ton award 
  # point into star i on 
  # 
  geom_point(
    data = plot_data %>%
            filter(most_profitable == "Most Profitable" &
                    !is.na(date)),
    aes(
      reorder(theatre, desc(date)),
      date,
      size = profits,
      color = award
    ),
    alpha = 0.79,
    shape = "☆"
  ) +
  scale_size(
    range = c(16,25.5)
  )+
  scale_x_discrete(
    position = "top"
  ) +
  cowplot::theme_minimal_hgrid()+
  labs(
    x = NULL, y = NULL,
    title = "How have theatres been doing with their most profitable musicals"
  )+
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "#101420"),
    axis.text.x = element_markdown(),
    panel.grid.major = element_blank()
    )

```
```{r}
print('&#10032')☆
```



