---
title: "Untitled"
author: "Tu"
date: "6/20/2020"
output: html_document
---

```{r}
library(tidyverse)
library(bbplot)
library(lubridate)
theme_set(theme_minimal())
```

```{r}
brewing_materials <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewing_materials.csv') %>%
  mutate(date = ymd(paste(year, month, 1))) %>%
  filter(year < 2016)
#beer_taxed <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_taxed.csv')
#brewer_size <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewer_size.csv')
#beer_states <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_states.csv')

```

```{r}
skimr::skim(brewing_materials)
```
```{r}
head(brewing_materials)
```
```{r}
brewing_materials %>%
  filter(year == max(year), month == max(month)) %>%
  filter(!str_detect(material_type, "Total")) %>% # take totals out
  ggplot() +
  geom_col(aes(x = month_current, y = reorder(type, month_current), fill = material_type)) # it lookslike we dont need three totals

```

```{r}
brewing_materials %>%
  filter(!str_detect(material_type, "Total")) %>%
  ggplot() +
  geom_col(aes(x = date, y = month_current, fill = type))
```

