---
title: "Untitled"
author: "Tu"
date: "6/22/2020"
output: html_document
---
```{r}
library(tidyverse)
theme_set(theme_minimal(base_family = "Bangers"))
```


```{r}
brewer_size <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewer_size.csv')
```

```{r}
# Missing value
under_1_2019 <- brewer_size %>%
  replace_na(list(total_barrels = 0, total_shipped = 0)) %>%
  filter(year == 2019 & brewer_size == "Under 1 Barrel") %>%
  group_by(year, brewer_size) %>%
  summarise_all(sum) %>%
  ungroup()

brewer_size <- rbind(brewer_size, under_1_2019) %>%
                na.omit()
```




```{r}
brewer_size %>%
  filter(brewer_size != "Total", !is.na(total_barrels)) %>%
  mutate(brewer_size = fct_lump(brewer_size, 5, w = total_barrels),
         barrel_number = coalesce(parse_number(as.character(brewer_size)), 1),
         brewer_size = fct_reorder(brewer_size, barrel_number)) %>%
  ggplot(aes(year, total_barrels, fill = brewer_size)) +
  geom_col()
```

```{r}
df_brew <- brewer_size %>%
  filter(
    brewer_size %in% c("Under 1 Barrel", "1 to 1,000 Barrels") 
  ) %>%
  mutate(
    year_mod = year + (year %% min(year, na.rm = T)) + 1
  ) %>%
  group_by(year, year_mod) %>%
  summarise(
    n_of_brewers = sum(n_of_brewers),
    total = sum(total_barrels)
  ) %>%
  ungroup() %>%
  mutate(
    label = glue::glue("{format(round(total/10^6, 2), nsmall = 2)}M")
  )
```
```{r}
df_ticks <-
  df_brew %>% 
  slice(rep(1, each = 5)) %>% 
  mutate(
    tick = seq(0.25*10^6, 1.25*10^6, by = 2.5*10^5),
    label = c("0.25", "0.50", "0.75", "1.00", "1.25")
  ) %>% 
  filter(tick < total - 50000)
  
set.seed(2)
df_brewers <-
  df_brew %>% 
  slice(rep(1, each = floor(n_of_brewers / 100))) %>% 
  mutate(
    dots_brewer = runif(n_of_brewers, 20000, total - 20000),
    dot_size = runif(n_of_brewers, 0, 1)
  )
```


```{r}
showtext::showtext_auto()
df_brew %>%
  ggplot(aes(year_mod, total)) +
  # 中间真空区
  geom_segment(data = df_brew %>% slice(1),
               aes(x = year_mod - .6, xend = year_mod + .6, yend = total),
               colour = "white", size = 35) +
  # bars
  geom_col(fill = "#f9e556", width = 1.2) +
  
  # bubbles
  geom_jitter(data = df_brewers,
              aes(year_mod, dots_brewer),
              position = position_jitter(width = .38, seed = 1),
              shape = 21,
              color = colorspace::darken("#f9e556", .17), #完成形状配色和草化
              stroke = .5) +
  geom_segment(data = df_brew,
               aes(x = year_mod + 0.655, 
                   xend = year_mod + 0.77,
                   y = total - 3500,  ## total only: - 2500
                   yend = total - 3500),  ## total only: - 2500)),
               size = 1.5, color = "white") +
  geom_text(aes(year_mod + 0.655, total - 3500, label = label),
             family = "Roboto Mono",
              fontface = "bold",
              color = "red",
              size = 4,
              hjust = 0) +
  geom_segment(data = df_brew,
                 aes(x = year_mod + .655,
                     xend = year_mod + .77,
                     y = 3500,
                     yend = 3500),
                 color = "white",
                 size = 1.5) +
    geom_text(aes(year_mod + .83, 
                  3500,
                  label = "0.00"),
              family = "Roboto Mono",
              fontface = "bold",
              color = "white",
              size = 4,
              hjust = 0) +
    geom_segment(data = df_ticks,
                 aes(x = year_mod + .675,
                     xend = year_mod + .78,
                     y = tick,
                     yend = tick),
                 color = "white",
                 size = .8) +
    scale_x_continuous(expand = c(.005, .005),
                       limits = c(NA, max(df_brew$year_mod) + 1.2),
                       breaks = seq(min(df_brew$year_mod), max(df_brew$year_mod), by = 2),
                       labels = c(min(df_brew$year):max(df_brew$year))) +
    scale_y_continuous(expand = c(.005, .005),
                       limits = c(0, 1750000)) +
    scale_size(range = c(2, 5), guide = F) +
    labs(x = NULL, y = NULL) 

```

